### ISSUE TITLE
Does not compile with threaded perls (0.03, 0.04)

### ISSUE THREAD

**Issue by eserte** [pine/p5-Text-Diff-Unified-XS#2]
See subject. Sample report: http://www.cpantesters.org/cpan/report/1c031a0c-cc1a-11e6-9d2b-fef08e6bb8a7

**Comment by pine** [comment]
Thanks! I've fixed. https://github.com/pine/p5-Text-Diff-Unified-XS/commit/f4e00d64902b760ed44b23de2ca0ab99a23f07f9
